--addEventHandler('onClientResourceStart',resourceRoot,function () 
function carregamento()
txd = engineLoadTXD( '18.txd' ) 
engineImportTXD( txd, 1210) 
dff = engineLoadDFF('18.dff', 1210) 
engineReplaceModel( dff, 1210)
end--)
addEvent( "Carregar-mods", true )
addEventHandler( "Carregar-mods", root, carregamento )
